In [1]:
my_string = "hello world"

In [2]:
print(my_string)

hello world


##Playing with slices
syntax of a slice: `my_string[start:end]`

In [5]:
my_string[0:1]

'h'

In [6]:
my_string[0:6]

'hello '

In [7]:
my_string[6:11]

'world'

Here is how to know the length of a string: `len()`

In [8]:
len(my_string)

11

In [11]:
my_string[0:(len(my_string)-1)]

'hello worl'

To access the last element, use index -1

In [13]:
my_string[0:-1]

'hello worl'

You can also do slices as: `start:end:step` ... and a -1 step goes backwards

In [15]:
my_string[::-1]

'dlrow olleh'

In [16]:
string = "banana"

In [17]:
print(string)

banana


In [19]:
string[1:2]

'a'

In [22]:
string[1:4]

'ana'

In [23]:
string[3:len(string)]

'ana'

In [24]:
string[-1]

'a'

##Slicing on NumPy arrays
Arrays are the essential data structure in numerical computing! They are available to you via the `numpy` library. Load the library like this:

In [25]:
import numpy

In [26]:
x = numpy.array([2, 4, 6, 8])

In [27]:
x[0]

2

In [28]:
x[1:3]

array([4, 6])

In [43]:
x = numpy.linspace(0,100,26)

In [33]:
print(x)

[   0.    4.    8.   12.   16.   20.   24.   28.   32.   36.   40.   44.
   48.   52.   56.   60.   64.   68.   72.   76.   80.   84.   88.   92.
   96.  100.]


In [34]:
x[3:12]

array([ 12.,  16.,  20.,  24.,  28.,  32.,  36.,  40.,  44.])

In [36]:
y = numpy.arange(0,100.0,4)
print(y)

[  0.   4.   8.  12.  16.  20.  24.  28.  32.  36.  40.  44.  48.  52.  56.
  60.  64.  68.  72.  76.  80.  84.  88.  92.  96.]


Or as integers...

In [38]:
x2 = numpy.linspace(0,100,26, dtype = int)
print(x2)

[  0   4   8  12  16  20  24  28  32  36  40  44  48  52  56  60  64  68
  72  76  80  84  88  92  96 100]


In [39]:
y2 = numpy.arange(0,100,4)
print(y2)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92 96]


In [40]:
type(x)

numpy.ndarray

In [44]:
type(x[0])

numpy.float64

In [42]:
type(x2[0])

numpy.int64